### ISSUE TITLE
General TODO list for 1.0

### ISSUE THREAD

**Issue by caseif** [LapisBlue/Nocturne#4]
This issue is meant to track the general tasks which must be completed before an initial release will be possible.

### Functionality
- [x] Implement "Rename" context menu item for selectable members - dc67066 & 3dde410
- [x] Display selected member when applicable - f0d96bd
- [x] Add "Reset name" context menu item for selectable members - fcb46f79
- [x] Display decompiled code when class is selected from sidebar - 88db668
- [x] Allow "jump to" feature for selectable class names - cb917a1
- [x] Implement syntax highlighting - 7df7213 & 5757f41

### Shortcomings
- [x] #6 Resetting names via GUI does not update mappings - 26e0b26
- [x] #7 Mappings should not be immutable - c1ba0a1
- [x] Focus existing tab if possible instead of opening new one - f3b6cbc
- [x] Close open tabs when JAR is unloaded - b952b36
- [x] Fix deobfuscated mappings in sidebar not opening source - 34ecbfb
- [x] Renaming classes does not update tree views in sidebar - bd011b1
- [x] Panes in right sidebar are useless - replace or remove - 460e2e6
- [x] Hierarchy duplicate element assertion does not consider identically named directories and classes - fe85e80
- [x] Class processor ignores inheritance - c86bdaf + many others
- [x] `SelectableMember` does not handle inner classes properly - 6b1a9c6
- [x] Duplicate deobfuscated names should not be allowed - ba4af8b & e21ca6d
- [x] Selectable import statements are quirky - fb58ee5
- [x] Implicit inherited methods are not handled properly - 062819c
- [x] Implicit inherited fields are not handled properly - 2b79390

This list is not final and is subject to change over time. The issue will be considered complete upon the release of version 1.0.0.

**Comment by jamierocks** [comment]
The context menu is there, just not functionable.

**Comment by caseif** [comment]
@jamierocks Yes, that's what I mean when I say it needs to be implemented.

**Comment by jamierocks** [comment]
Ah :P
